C: 0.3
b: -80
batch_size: 160
beta1: 0.9
beta2: 0.999
code: 0429_8_4_repeat1
elossIndexStr: MSE
gpu: 0
k_eLoss: 1.0
light_ch: 96
logGrad: false
logGrad_everyIter: true
logHist_everyIter: true
logImage_everyIter: false
logLoss_everyIter: true
logVar_everyIter: true
log_step: 30
lossIndexStr: eLoss1.10.2
lr: 0.0005
lr_update_step: 500
model_save_step: 20
model_test_step: 5
n_update_step: 1
num_epochs: 20
num_workers: 2
obj: PMs_phone1_3_RGBFrame
pixel_batchSize: 256
result_save_path: ./result/0429_8_4_repeat1
threshold_log: 20.0
trainDataShuffle: 'False'
trainTime: '2022-05-04 21:54:47'
use_tensorboard: true
